### ISSUE TITLE
Плохая практика писать вложенные тернарные операторы

### ISSUE THREAD

**Issue by masiya255** [namik-gamedev/weather-react-app#1]
https://github.com/namik-gamedev/weather-react-app/blob/3bc58c7766087a4fd2b506a4908ae8977c2c3958/src/App.jsx#L48

![image](https://user-images.githubusercontent.com/11834317/222080042-bd2ecc39-5b08-4410-ab7d-113ad53998b3.png)

**Comment by namik-gamedev** [comment]
was fixed.
